### ISSUE TITLE
Rules seconds missing

### ISSUE THREAD

**Issue by mariusvaida** [mycontroller-org/mycontroller#214]
When i set a rule, i cannot set the seconds, however when i'm saving it, it puts a value for them
![seconds](https://cloud.githubusercontent.com/assets/19683063/15715613/c7c97102-2827-11e6-9a5d-e313c44a3f65.jpg)
![missing seconds](https://cloud.githubusercontent.com/assets/19683063/15715612/c7c3458e-2827-11e6-96d0-05d654427363.jpg)

It is the expected behavior? If so, it's not a big issue, but at least it should set the seconds to zero.

Windows 10 64bit/Chrome 50.0.2661.102

**Comment by jkandasa** [comment]
@mariusvaida https://github.com/patternfly/angular-patternfly not supported yet for `angular-ui` version 1.x. Hence I am unable to give support for seconds. I will make seconds to zero `0` by default. When this issue fixed in https://github.com/patternfly/angular-patternfly we will allow to change seconds also.

**Comment by mariusvaida** [comment]
This solves is. Thanks!
