### ISSUE TITLE
Support for DualOptiboot-bootloader

### ISSUE THREAD

**Issue by jkandasa** [mycontroller-org/mycontroller#25]
Right now MyController supports only MYSBootloader to upgrade firmware. It will be nice to support for DualOptiboot-bootloader also as many people using this.

**Comment by jkandasa** [comment]
I do not have any hardware to test this feature. I believe this fix will work properly.

**Comment by TheCranston** [comment]
My nodes are LowPowerLab Moteinos with DualOptiboot loaded.  The alpah5 controller will now send firmware to the node which it wouldn't do before.  However the boot loader does not install that new firmware on reboot, so I'm thinking that the "magic" signature was not written at the beginning.  according to Felix's git pages for the boot loader, it checks for a new sketch flash image signature and size starting at address 0: FLXIMG:9999:XXXXXXXXXXX where: - 'FLXIMG' is fixed signature indicating FLASH chip contains a valid new flash image to be burned - '9999' are 4 size bytes indicating how long the new flash image is (how many bytes to read) - 'XXXXXX' are the de-hexified bytes of the flash pages to be burned - ':' colons have fixed positions (delimiters)

**Comment by jkandasa** [comment]
@TheCranston Thank you to test this feature and analysis! I believe MySensors should handle image signatures([code](https://github.com/mysensors/Arduino/blob/documentation/libraries/MySensors/MySensor.cpp#L767)). Nothing to do MyController. As per my understanding, once firmware download done from MyController if our node reboots automatically definitely signature has been written

**Comment by TheCranston** [comment]
I think I understand what you are saying, MyController just submits the .hex file for upload to the node and the underlying MySensors library handles it.  Got it.  I'm not a java programmer, so I'm a little at a loss for debugging.  Thanks for the link to the code, that shows it clearly.  My process was to install a new firmware into MyController and then go to node list and click on firmware upload.  I can see the serial traffic via the LEDs.  It didn't appear to reboot after the upload, so I manually rebooted the node.  My understanding is that the reboot would trigger the DualOptiboot firmware flash process.  no such luck.  I'm on 1.5 API of MySensors library.  A few more attempts and the same result... I'll take this over to MySensors as it appears the issue is either mine or the library.  :)  MyController is really sweet!  Thanks for this great work.

**Comment by jkandasa** [comment]
@TheCranston Thank you for your effort on this. As I do not have hardware to test this feature I'm unable to help you to resolve this issue. I'm sorry. Let me get this hardware soon and try to fix this issue (if issue with MyController side) on 0.0.2-alpha6 build. 

I really appreciate your valuable time!!

**Comment by ghvader** [comment]
@TheCranston / Jeeva - I'm in the same situation.
however using MYScontroller this works fine.
so it can't be the mysensors library at fault.
I think there is an app that is "like" wireshark, that you can watch the
packets,
perhaps i'll look into that and see if i can't figure out what is going on.

**Comment by jkandasa** [comment]
@ghvader Thank you!! Let me debug MyController to find out issue.

**Comment by TheCranston** [comment]
@ghvader / @jkandasa 
I found the issue..  At least for my script.  I was using the watchdog timer directly and that was causing the reboot after firmware load to fail.  I took out my watchdog code in the script and everything now works correctly.  I'm not sure what the interaction was that caused the failure, but at least now I can do OTA updates of the code on my nodes.

**Comment by jkandasa** [comment]
@TheCranston OTA updates working good with `DualOptiboot-bootloader` + MyController?

**Comment by TheCranston** [comment]
@jkandasa It sure is.  my sketch was directly using the watchdog which was causing it to fail. I removed my watchdog code and everything started to work correctly.
