### ISSUE TITLE
[Bug?] Response to mysensor request is wrong

### ISSUE THREAD

**Issue by cimba007** [mycontroller-org/mycontroller#264]
Gateway: Nodeid 0
Sensor: Nodeid 20

Sensor uses the following code:

```
request(0,V_ARMED,0);
```

The result received is the V_ARMED value of the sensor node .. not as originally requested the one of gateway.

The button toggle is working as expected. Only if i change the value on the sensor node on mycontroller then the real sensor received the update.

If i change the switch on mycontroller of the gateway .. no message is received by node 20 .. as expected!!

**Comment by jkandasa** [comment]
@cimba007 Is this happen all the time? or sometimes only?

**Comment by cimba007** [comment]
I will try an simple test sketch to verify!

**Comment by jkandasa** [comment]
@cimba007 AFAIK, earlier version of MySensors.org does not support any sensors. It was acting only as a gateway. never control any sensors. `request` feature was designed that time. It was designed as, if some one request data from gateway(default), it will forward the request to controller. If do a request from other than gateway (other destination - like you have mentioned) it will be forwarded to that particular destination node(this operation happens without controller knowledge).

But recently MySensors introduced sensors support on Gateway too. I hope this `request` feature not redesigned yet. I believe it is tough to change this logic. Because gateway's primary response is, if some one asked any request with the destination id as `0`, gateway believes it is for controller.

In your case it happens as follows,

* You requested sensor `0` of `V_ARMED` status and destination is `0` (gateway id)
* Gateway thinks this message for controller(as per current design) and sent to controller
* controller reads this message as `50;0;2;0;15;`(`node-id;child-sensor-id;message-type;ack;sub-type;payload`), which means `nodeId=50` requested `V_ARMED` data of `SensorId 0`. It looks in db and nothing found. It creates entry for this node/sensor/variable and sends some default value(MyController designed like if it receives message from new device, create an entry for that).

**Comment by cimba007** [comment]
Thanks for the very good explanation at the mysensor.net forum.

From all I have tested and read the best solution (at least I think) would be to clearly differentiate between request from controller and request from node/gateway.

**Comment by cimba007** [comment]
Some time has passed and now I have found some motivation ton continue my projects with mysensors.

My initial problem is still there and I found a project where I need a solution for that:

I currently got one LCD-display which is connected to the controller .. working fine so far.

But now I want to display some values on the LCD like .. is some security sensor tripped, what is the temperature .. etc.

What would be the best way to implement this? It seems unlogical to change all my sensor-nodes and add an extra send-routine to pass the data to the LCD.

Is there another way for my lcd-node to request arbitrary node-data from the controller?

**Comment by jkandasa** [comment]
@cimba007 Create script and send values to your LCD. In the script take values from sensor variables.

**Comment by cimba007** [comment]
I am not this familiar with the api. It would be very nice if you could create a simple example I could use. Thank you jkandasa for your hard work! ;-)

**Comment by jkandasa** [comment]
@cimba007 Can you list your requirement. i will create a sample script.

**Comment by cimba007** [comment]
HI Jeeva,

thanks for your response. My current solution is using the "forward 
payload" feature. An script would be an alternative solution which I 
would gladly learn about.
My requirement is like this:

- Every 10 seconds take current/last value of sensor-variable XYZ and 
send it to the "LCD"-Node.
- It would be very nice if I could even send history values too! e.g. 
Last Temperature Value, avg over last hour, avg over last day.

I would help me even more if you could give me some tips on how to query 
these values (just like from script) from any external resource. (e.g. a 
GET-REST to mycontroller)
so I can use this data on some non mysensor-projects too. (e.g. ESP8266 
WIFI Node (Arduino)).


Best regards and thanks in advance!

Marc



Am 01.02.2017 04:40 schrieb Jeeva Kandasamy:

**Comment by jkandasa** [comment]
@cimba007 kindly refer http://forum.mycontroller.org/topic/174/help-logging-data
