### ISSUE TITLE
'Last seen' on dashboards [Feature request]

### ISSUE THREAD

**Issue by ragflyer** [mycontroller-org/mycontroller#342]
I've seen #219 but would like to propose another feature:
When looking at a sensor graph or status you would like to know how old is the dataset directly, so why not show this information right there. I imagine 3 options when adding a sensor to a dashboard:

- Do not show last seen
- Show last seen (maybe next to the headline on graphs or below the data on other sensors)
- Show tooltip only (maybe show a sandglass next to the eye icon and show the last seen info on hover)

What do you think?

**Comment by jkandasa** [comment]
@ragflyer 
> Show tooltip only (maybe show a sandglass next to the eye icon and show the last seen info on hover)

I support this option.

**Comment by Redferne** [comment]
Tooltips are not working that good on Chrome on Android phones AFAIK. 

I have very similar question. Is it possible to filter out the complete sensor path when displaying on Dashboard? 
![20170107_083239](https://cloud.githubusercontent.com/assets/2379821/21740246/225af7c4-d4b4-11e6-867d-7c84196148e9.png)
The red text is completely superflous and almost annoying, since it displays data not needed in a Dashboard. Green text would describe the sensor value? Or maybe blue text is enough since it is customizable.

What do you think? Sorry for hijacking your issue @ragflyer

**Comment by jkandasa** [comment]
if you guys still interested on this change, kindly reopen this issue

**Comment by HiFiJ** [comment]
Hi everyone,

I second this (a last seen status on the dashboard) strongly. 
Just my personal use case: I am learning MySensors and building own PCBs/sensors and am constantly interested in the stability of the sensor network (e.g. as I test different battery options/PMICs/antenna designs and so on) and find myself constantly tapping on my phone to get into the node details to check if the nodes are still online, which is very cumbersome.

Thanks for your efforts, MyController is really great!

Joost
