### ISSUE TITLE
Removing firmware type before removing firmware fails

### ISSUE THREAD

**Issue by githubcdr** [mycontroller-org/mycontroller#9]
Great software, really impressed!

Found a small bug, if a users deletes a "firmware type"  which is in use, the user won't be able to delete the "firmware itself.

Adding the type and will not resolve this.

**Comment by jkandasa** [comment]
@githubcdr Thank you to make MyController.org to better quality.

Adding type will not resolve this issue because the type id is auto generated and we will not get the same id again. However we should provide an option to enter type id and version id manually. To track that issue I have created another issue #11
